name: Daily Pokemon Scraper

on:
  schedule:
    - cron: '0 11 * * *'  # every day at 08:00 UTC
  workflow_dispatch:       # allows manual run

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver

      - name: Run scraper
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          PYTHONPATH: src
        run: python src/scraper/__main__.py

      - name: Upload page HTML artifacts
        if: always()  # upload even if script fails
        uses: actions/upload-artifact@v3
        with:
          name: page-html
          path: '*.html'