name: Daily Pokemon Scraper

on:
  schedule:
    - cron: '0 11 * * *'  # every day at 08:00 UTC
  workflow_dispatch:       # allows manual run

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

#      - name: Install Chrome and Chromedriver
#        run: |
#          sudo apt update
#          sudo apt install -y chromium-browser chromium-chromedriver

      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo mkdir -p /etc/apt/sources.list.d
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get -y install google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROMEDRIVER_VERSION="143.0.7499.40"
          echo "Installing ChromeDriver version: $CHROMEDRIVER_VERSION"
          wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          chmod +x chromedriver-linux64/chromedriver
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/

      - name: Run scraper
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          PYTHONPATH: src
        run: python src/scraper/__main__.py

      - name: Upload page HTML artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: page-html
          path: '*.html'
